### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by asan-emirsaleh** [PacktPublishing/Deep-Learning-for-Genomics-#1]
Please take a look at the README of this repository.
It seems be referred to [Actionable Insights with Amazon QuickSight](https://www.packtpub.com/product/actionable-insights-with-amazon-quicksight/9781801079297)
but not to Deep-Learning-for-Genomics

**Comment by rajat-packt** [comment]
Hey @asan-emirsaleh the links in the README have been updated.
I'll be closing this issue now
